USE [master]
GO
/****** Object:  Database [BD_PROPERTIES]    Script Date: 20/07/2021 9:18:56 p. m. ******/
CREATE DATABASE [BD_PROPERTIES]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BD_PROPERTIES', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BD_PROPERTIES.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BD_PROPERTIES_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BD_PROPERTIES_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [BD_PROPERTIES] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BD_PROPERTIES].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BD_PROPERTIES] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BD_PROPERTIES] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BD_PROPERTIES] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BD_PROPERTIES] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BD_PROPERTIES] SET ARITHABORT OFF 
GO
ALTER DATABASE [BD_PROPERTIES] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BD_PROPERTIES] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BD_PROPERTIES] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BD_PROPERTIES] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BD_PROPERTIES] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BD_PROPERTIES] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BD_PROPERTIES] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BD_PROPERTIES] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BD_PROPERTIES] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BD_PROPERTIES] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BD_PROPERTIES] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BD_PROPERTIES] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BD_PROPERTIES] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BD_PROPERTIES] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BD_PROPERTIES] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BD_PROPERTIES] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BD_PROPERTIES] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BD_PROPERTIES] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [BD_PROPERTIES] SET  MULTI_USER 
GO
ALTER DATABASE [BD_PROPERTIES] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BD_PROPERTIES] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BD_PROPERTIES] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BD_PROPERTIES] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BD_PROPERTIES] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BD_PROPERTIES] SET QUERY_STORE = OFF
GO
USE [BD_PROPERTIES]
GO
/****** Object:  User [user_prop]    Script Date: 20/07/2021 9:18:56 p. m. ******/
CREATE USER [user_prop] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  User [usrProp]    Script Date: 20/07/2021 9:18:56 p. m. ******/
CREATE USER [usrProp] FOR LOGIN [usrProp] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [user_prop]
GO
ALTER ROLE [db_owner] ADD MEMBER [usrProp]
GO
ALTER ROLE [db_datareader] ADD MEMBER [usrProp]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [usrProp]
GO
/****** Object:  Table [dbo].[Owner]    Script Date: 20/07/2021 9:18:56 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Owner](
	[idOwner] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](500) NOT NULL,
	[address] [nvarchar](500) NOT NULL,
	[photo] [nvarchar](500) NOT NULL,
	[birthdate] [date] NOT NULL,
 CONSTRAINT [PK_Owner] PRIMARY KEY CLUSTERED 
(
	[idOwner] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Property]    Script Date: 20/07/2021 9:18:56 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Property](
	[idProperty] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](2000) NOT NULL,
	[address] [nvarchar](2000) NOT NULL,
	[price] [decimal](18, 4) NOT NULL,
	[codeInternal] [nvarchar](500) NOT NULL,
	[year] [int] NOT NULL,
	[idOwner] [int] NOT NULL,
 CONSTRAINT [PK_Property] PRIMARY KEY CLUSTERED 
(
	[idProperty] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PropertyImage]    Script Date: 20/07/2021 9:18:56 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PropertyImage](
	[idPropertyImage] [int] IDENTITY(1,1) NOT NULL,
	[idProperty] [int] NOT NULL,
	[file] [nvarchar](2000) NOT NULL,
	[enabled] [bit] NOT NULL,
 CONSTRAINT [PK_PropertyImage] PRIMARY KEY CLUSTERED 
(
	[idPropertyImage] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PropertyTrace]    Script Date: 20/07/2021 9:18:56 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PropertyTrace](
	[IdPropertyTrace] [int] IDENTITY(1,1) NOT NULL,
	[dateSale] [datetime] NOT NULL,
	[name] [nvarchar](2000) NOT NULL,
	[value] [decimal](18, 4) NOT NULL,
	[tax] [decimal](18, 2) NOT NULL,
	[idProperty] [int] NOT NULL,
 CONSTRAINT [PK_PropertyTrace] PRIMARY KEY CLUSTERED 
(
	[IdPropertyTrace] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Property]  WITH CHECK ADD  CONSTRAINT [FK_Property_Owner] FOREIGN KEY([idOwner])
REFERENCES [dbo].[Owner] ([idOwner])
GO
ALTER TABLE [dbo].[Property] CHECK CONSTRAINT [FK_Property_Owner]
GO
ALTER TABLE [dbo].[PropertyImage]  WITH CHECK ADD  CONSTRAINT [FK_PropertyImage_Property] FOREIGN KEY([idProperty])
REFERENCES [dbo].[Property] ([idProperty])
GO
ALTER TABLE [dbo].[PropertyImage] CHECK CONSTRAINT [FK_PropertyImage_Property]
GO
ALTER TABLE [dbo].[PropertyTrace]  WITH CHECK ADD  CONSTRAINT [FK_PropertyTrace_Property] FOREIGN KEY([idProperty])
REFERENCES [dbo].[Property] ([idProperty])
GO
ALTER TABLE [dbo].[PropertyTrace] CHECK CONSTRAINT [FK_PropertyTrace_Property]
GO
USE [master]
GO
ALTER DATABASE [BD_PROPERTIES] SET  READ_WRITE 
GO
